# 1. The Numpy Package

## 1.1 Numpy Array Basics

In [3]:
import numpy as np #import numpy

In [4]:
l = list(range(1,11)) #create a list
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
my_array = np.array(l) #transform list into a numpy array (ndarray)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(my_array)

numpy.ndarray

In [7]:
for i in my_array: # same as lists, ndarrays store multiple elements (is iterable)
    print(i)

1
2
3
4
5
6
7
8
9
10


In [8]:
l = [1, 2.5, "Dog", True] #lists can store different datatypes

In [9]:
for i in l:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [10]:
a = np.array(l) #in ndarrays, all elements must have same datatype; numpy transforms automatically
a

array(['1', '2.5', 'Dog', 'True'], dtype='<U32')

In [11]:
for i in a:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [12]:
b = np.array([1., "2", 3])
b

array(['1.0', '2', '3'], dtype='<U32')

In [13]:
type(b)

numpy.ndarray

In [14]:
b.dtype #can check single datatype of all elements with attribute .dtype

dtype('<U32')

## 1.2 Numpy Array (element-wise operations / vectorization)

In [15]:
import numpy as np

In [16]:
np.arange(1,11) #create new ndarray from 1(incl.) to 11(excl.)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(1,11,2) #only every second number is created

array([1, 3, 5, 7, 9])

In [18]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [21]:
l*2 #this is not an element-wise operation

[1, 2, 3, 4, 1, 2, 3, 4]

**Important**

In [22]:
l1 = [] #element-wise operations with lists require a bunch of code
for i in l:
    l1.append(i*2)
l1

[2, 4, 6, 8]

In [23]:
a = np.arange(1,5) #create ndarray from 1 to 4 (both including)
a

array([1, 2, 3, 4])

In [24]:
a * 2 #element-wise (vectorized) operations are pretty simple with ndarrays

array([2, 4, 6, 8])

In [25]:
a + 2 #addition works as well

array([3, 4, 5, 6])

In [26]:
a**2 #all elements squared

array([ 1,  4,  9, 16])

In [27]:
2**a #can serve as exponent as well

array([ 2,  4,  8, 16])

In [28]:
np.sqrt(a) #square root of all elements

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [29]:
np.exp(a) #exponentiation with e

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [30]:
np.log(a) #natural logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
a.sum() #sum of all elements (ndarray method)

10

In [32]:
np.sum(a) #sum of all elements

10

In [33]:
sum(a)

10

In [34]:
a.size #number of elements in ndarray (ndarray attribute)

4

In [35]:
len(a)

4

In [36]:
b = np.array([-2, -1, -0.5, 0, 1, 2, 3.5])
b

array([-2. , -1. , -0.5,  0. ,  1. ,  2. ,  3.5])

In [ ]:
np.abs(b) #absolute values of all elements

In [ ]:
c = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
c

In [ ]:
np.ceil(c) #element-wise rounding up

In [ ]:
np.floor(c) #element-wise rounding down

In [ ]:
np.around([-3.23, -0.76, 1.44, 2.65, ], decimals = 0) #evenly round all elements to the given number of decimals.

## 1.3 Numpy Array (Indexing and Slicing)

In [38]:
import numpy as np

In [37]:
a = np.arange(1,11) #array from 1 to 10 (incl.)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
a[0] #first element at index position 0 (zero-based indexing!)

1

In [40]:
a[1] #second element (index position 1)

2

In [41]:
a[-1] #last element

10

In [42]:
list(enumerate(a)) #list of index,value tuples

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [43]:
a[2:6] #slicing from index position 2 (incl.) till position 6 (excl.)

array([3, 4, 5, 6])

In [44]:
a[:] #all elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
a[:5] #all elements until index position 5 (excl.)

array([1, 2, 3, 4, 5])

In [46]:
a[6:] #all elements from index position 6 (incl.) till the last element (incl.)

array([ 7,  8,  9, 10])

In [47]:
a[::2] #every second element, starting from first element

array([1, 3, 5, 7, 9])

In [48]:
a[::3] #every third element, starting from first element

array([ 1,  4,  7, 10])

In [49]:
a[2::3] #every third element, starting from third element (index position 2)

array([3, 6, 9])

In [50]:
a[0] = 100 #ndarrays are mutable, changing first element to 100
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [51]:
a[-1] = 101 #changing last element to 101
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9, 101])

In [52]:
a[2:5] = 50 #in contrast to lists, ndarrays allow braodcasting, assigning one new value to multiple elements
a

array([100,   2,  50,  50,  50,   6,   7,   8,   9, 101])

In [53]:
a[2:5] = [50, 51, 52] #assigning multiple new values to multiple elements
a

array([100,   2,  50,  51,  52,   6,   7,   8,   9, 101])

In [54]:
a = np.arange(1,11) #creating new ndarray a
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
b = a[2:8] # making a slice of ndarray a and assign new variable b,
b
#try b =a[2:8].copy() afterwords

array([3, 4, 5, 6, 7, 8])

In [56]:
b[0] = 100 #changing first element of ndarray b
b

array([100,   4,   5,   6,   7,   8])

In [ ]:
a #respective element of ndarray a has changed as well!!!

In [57]:
l = list(range(1,11)) #lists behave differently
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [58]:
m = l[2:8] #here a copy of the slice of l is created
m

[3, 4, 5, 6, 7, 8]

In [59]:
m[0] = 100 #changing first element of slice m
m

[100, 4, 5, 6, 7, 8]

In [60]:
l #no effect on l !!!

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## 1.4 Numpy Array (Shape and multiple Dimensions)

In [61]:
import numpy as np

In [62]:
a = np.arange(1,13) #creating array from 1 to 12
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
type(a)

numpy.ndarray

In [64]:
a.dtype

dtype('int64')

In [65]:
a.shape #one-dimensional array, 12 elements in one dimension (vector)

(12,)

In [66]:
a = a.reshape(2,6) #reshaping a: 2 rows / 6 columns

In [67]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [68]:
a.shape # two-dimensional array: 2 rows / 6 columns (matrix)

(2, 6)

In [69]:
a = a.reshape(6,2) # two-dimensional array: 6 rows / 2 columns
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:
a.shape

(6, 2)

In [71]:
a + 100 #element-wise operations still work

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108],
       [109, 110],
       [111, 112]])

In [72]:
a = a.reshape(2,2,3) #creating a three-dimensional array
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
a.shape

(2, 2, 3)

In [75]:
b = np.arange(1,101).reshape(20,5) #creating 2-dim ndarray with one line of code
b

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

## 1.5 Numpy Array (Indexing and Slicing multi-dimensional arrays)

In [76]:
import numpy as np

In [77]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
a = a.reshape(3,4) #creating matrix with 3 rows and 4 columns
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
a[0] #first row (index position 0)

array([1, 2, 3, 4])

In [80]:
a[1] #second row (index position 1)

array([5, 6, 7, 8])

In [81]:
a[2] #third row (index position 2)

array([ 9, 10, 11, 12])

In [82]:
a[-1] #last row (index position -1)

array([ 9, 10, 11, 12])

In [83]:
a[1][1] #second row, second column

6

In [84]:
a[1,1] #more convenient in one square bracket

6

In [85]:
a[2,-1] #third row, last column

12

In [86]:
a[:,0] #all rows, first column

array([1, 5, 9])

In [87]:
a[:,1] #all rows, second column

array([ 2,  6, 10])

In [88]:
a[:,-1] #all rows, last column

array([ 4,  8, 12])

In [89]:
a[:2,1:3] #first two rows, column two and three

array([[2, 3],
       [6, 7]])

In [90]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
a.T #Transpose: switching axes (attribute)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [92]:
a.transpose() #same (method)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [93]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
a[:,-1] = a[:,-1] /4 #changing slice inplace

In [95]:
a

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  2],
       [ 9, 10, 11,  3]])

In [96]:
a = np.arange(1,13).reshape(3,4) #creating a 3x4 matrix
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
a.sum() #sum over all elements in matrix

78

In [98]:
a.sum(axis = 0) #sum of each column

array([15, 18, 21, 24])

In [99]:
a.sum(axis = 1) #sum of each row

array([10, 26, 42])

In [100]:
a.cumsum() #cumulative sum of all elements

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [101]:
a.cumsum(axis = 0) #cumulative sum for each column

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]])

In [102]:
a.cumsum(axis = 1) #cumulative sum for each row

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]])

In [103]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
a.prod() #product over all elements

479001600

In [105]:
a.prod(axis = 0) #product over all elements in each column

array([ 45, 120, 231, 384])

In [106]:
a.prod(axis = 1) #product over all elements in each row

array([   24,  1680, 11880])